import { BadRequestException, Injectable, NotFoundException } from "@nestjs/common";
import type { Prisma } from "@prisma/client";
import { PrismaService } from "../prisma/prisma.service.js";

export type PartyRole = "buyer" | "seller";
export type PartyType = "individual" | "company";

export interface PartyMeta {
    id: string;
    name: string;
    partyType: string;
    aadhaarNumber: string | null;
    fileName: string | null;
    mimeType: string | null;
    size: number | null;
    aadhaarBackFileName: string | null;
    aadhaarBackMimeType: string | null;
    aadhaarBackSize: number | null;
    panNumber: string | null;
    panFileName: string | null;
    panMimeType: string | null;
    panSize: number | null;
    createdAt: string;
}

export interface DeedPartyItem {
    linkId: string;
    role: PartyRole;
    party: PartyMeta;
}

export interface NaxaMeta {
    id: string;
    deedId: string;
    fileName: string;
    mimeType: string;
    size: number;
    createdAt: string;
}

interface UploadedDoc {
    buffer: Buffer;
    originalname?: string;
    mimetype?: string;
}

const PARTY_META = {
    id: true,
    name: true,
    partyType: true,
    aadhaarNumber: true,
    fileName: true,
    mimeType: true,
    size: true,
    aadhaarBackFileName: true,
    aadhaarBackMimeType: true,
    aadhaarBackSize: true,
    panNumber: true,
    panFileName: true,
    panMimeType: true,
    panSize: true,
    createdAt: true,
} as const;

function toPartyMeta(r: {
    id: string;
    name: string;
    partyType: string;
    aadhaarNumber: string | null;
    fileName: string | null;
    mimeType: string | null;
    size: number | null;
    aadhaarBackFileName: string | null;
    aadhaarBackMimeType: string | null;
    aadhaarBackSize: number | null;
    panNumber: string | null;
    panFileName: string | null;
    panMimeType: string | null;
    panSize: number | null;
    createdAt: Date;
}): PartyMeta {
    return {
          id: r.id,
          name: r.name,
          partyType: r.partyType,
          aadhaarNumber: r.aadhaarNumber,
          fileName: r.fileName,
          mimeType: r.mimeType,
          size: r.size,
          aadhaarBackFileName: r.aadhaarBackFileName,
          aadhaarBackMimeType: r.aadhaarBackMimeType,
          aadhaarBackSize: r.aadhaarBackSize,
          panNumber: r.panNumber,
          panFileName: r.panFileName,
          panMimeType: r.panMimeType,
          panSize: r.panSize,
          createdAt: r.createdAt.toISOString(),
    };
}

/** Digits-only Aadhaar (strips spaces/dashes users may type). */
function normalizeAadhaar(raw: string): string {
    return (raw ?? "").replace(/[^0-9]/g, "");
}

/** Uppercase alphanumeric PAN (strips spaces/dashes users may type). */
function normalizePan(raw: string): string {
    return (raw ?? "").replace(/[^a-zA-Z0-9]/g, "").toUpperCase();
}

/** Bytes column value. Prisma's generated Bytes type is stricter than Node's Buffer under the current @types/node, so cast through the exact create-input field type. */
type PartyBytes = Prisma.PartyCreateInput["data"];
type NaxaBytes = Prisma.DeedNaxaCreateInput["data"];

/**
 * Aadhaar/PAN cards (reusable "people" or "companies", deduped by Aadhaar or
 * PAN number) and per-deed property maps (naxa). All bytes live in Postgres
 * because the API host has no persistent disk, so filesystem uploads
 * wouldn't survive a redeploy.
 */
@Injectable()
    export class DeedDocumentsService {
    constructor(private readonly prisma: PrismaService) {}

// ---- Parties (reusable people/companies, deduped by Aadhaar or PAN) ----

/** Search existing people/companies by name, Aadhaar number, or PAN number, for the reuse picker. */
async searchParties(query: string): Promise<PartyMeta[]> {
    const q = (query ?? "").trim();
    const digits = normalizeAadhaar(q);
    const pan = normalizePan(q);
    const rows = await this.prisma.party.findMany({
          where: q
          ? {
                  OR: [
                    { name: { contains: q, mode: "insensitive" } },
                            ...(digits ? [{ aadhaarNumber: { contains: digits } }] : []),
                            ...(pan ? [{ panNumber: { contains: pan } }] : []),
                            ],
          }
                  : {},
          orderBy: { name: "asc" },
          take: 20,
          select: PARTY_META,
    });
    return rows.map(toPartyMeta);
}

/** Aadhaar card (front) bytes for one person. */
async partyFile(id: string): Promise<{ fileName: string; mimeType: string; data: Buffer }> {
    const row = await this.prisma.party.findUnique({
          where: { id },
          select: { fileName: true, mimeType: true, data: true },
    });
    if (!row) throw new NotFoundException("Person not found.");
    if (!row.data) throw new NotFoundException("No Aadhaar card on file for this person.");
    return {
          fileName: row.fileName ?? "aadhaar",
          mimeType: row.mimeType ?? "application/octet-stream",
          data: Buffer.from(row.data),
    };
}

/** Aadhaar card (back) bytes for one person. */
async aadhaarBackFile(id: string): Promise<{ fileName: string; mimeType: string; data: Buffer }> {
    const row = await this.prisma.party.findUnique({
          where: { id },
          select: { aadhaarBackFileName: true, aadhaarBackMimeType: true, aadhaarBackData: true },
    });
    if (!row) throw new NotFoundException("Person not found.");
    if (!row.aadhaarBackData) throw new NotFoundException("No Aadhaar card (back) on file for this person.");
    return {
          fileName: row.aadhaarBackFileName ?? "aadhaar-back",
          mimeType: row.aadhaarBackMimeType ?? "application/octet-stream",
          data: Buffer.from(row.aadhaarBackData),
    };
}

/** PAN card bytes for one person/company. */
async panFile(id: string): Promise<{ fileName: string; mimeType: string; data: Buffer }> {
    const row = await this.prisma.party.findUnique({
          where: { id },
          select: { panFileName: true, panMimeType: true, panData: true },
    });
    if (!row) throw new NotFoundException("Person not found.");
    if (!row.panData) throw new NotFoundException("No PAN card on file for this person.");
    return {
          fileName: row.panFileName ?? "pan",
          mimeType: row.panMimeType ?? "application/octet-stream",
          data: Buffer.from(row.panData),
    };
}

// ---- Deed <-> Party links ----

async listDeedParties(deedId: string): Promise<DeedPartyItem[]> {
    const rows = await this.prisma.deedParty.findMany({
          where: { deedId },
          orderBy: { createdAt: "asc" },
          select: { id: true, role: true, party: { select: PARTY_META } },
    });
    return rows.map((r) => ({
          linkId: r.id,
          role: r.role as PartyRole,
          party: toPartyMeta(r.party),
    }));
}

/**
     * Attach a buyer/seller to a deed. Either reuse an existing person/company (by
     * partyId, or by an Aadhaar/PAN number that already exists) or create a new
     * one from an uploaded card. Creating requires a name plus the card matching
     * whichever number (Aadhaar and/or PAN) was given; reuse does not. The Aadhaar
     * back-side image is optional even when the front is given.
     * A person can appear on a deed only once — not as both buyer and seller.
     */
async addDeedParty(input: {
    deedId: string;
    role: PartyRole;
    partyId?: string;
    name?: string;
    partyType?: PartyType;
    aadhaarNumber?: string;
    panNumber?: string;
    file?: UploadedDoc;
    aadhaarBackFile?: UploadedDoc;
    panFile?: UploadedDoc;
}): Promise<DeedPartyItem> {
    let resolvedPartyId: string;

    if (input.partyId) {
          const found = await this.prisma.party.findUnique({
                  where: { id: input.partyId },
                  select: { id: true },
          });
          if (!found) throw new NotFoundException("Selected person not found.");
          resolvedPartyId = found.id;
    } else {
          const partyType: PartyType = input.partyType === "company" ? "company" : "individual";
          const aadhaar = input.aadhaarNumber ? normalizeAadhaar(input.aadhaarNumber) : "";
          const pan = input.panNumber ? normalizePan(input.panNumber) : "";

    if (aadhaar && aadhaar.length !== 12) {
          throw new BadRequestException("A valid 12-digit Aadhaar number is required.");
    }
          if (pan && !/^[A-Z]{5}[0-9]{4}[A-Z]$/.test(pan)) {
                  throw new BadRequestException("A valid 10-character PAN number is required.");
          }
          if (!aadhaar && !pan) {
                  throw new BadRequestException("Aadhaar number or PAN number is required.");
          }

    const existing = await this.prisma.party.findFirst({
          where: {
                  OR: [
                            ...(aadhaar ? [{ aadhaarNumber: aadhaar }] : []),
                            ...(pan ? [{ panNumber: pan }] : []),
                            ],
          },
          select: { id: true },
    });

    if (existing) {
          resolvedPartyId = existing.id;
    } else {
          const name = (input.name ?? "").trim();
          if (!name) throw new BadRequestException("Name is required for a new person.");
          if (aadhaar && !input.file) {
                  throw new BadRequestException("Aadhaar card image is required for a new person.");
          }
          if (pan && !input.panFile) {
                  throw new BadRequestException("PAN card image is required for a new person.");
          }
          const created = await this.prisma.party.create({
                  data: {
                            name,
                            partyType,
                            aadhaarNumber: aadhaar || null,
                            fileName: input.file ? (input.file.originalname ?? "aadhaar") : null,
                            mimeType: input.file ? (input.file.mimetype ?? "application/octet-stream") : null,
                            size: input.file ? input.file.buffer.length : null,
                            data: input.file ? (input.file.buffer as unknown as PartyBytes) : null,
                            aadhaarBackFileName: input.aadhaarBackFile ? (input.aadhaarBackFile.originalname ?? "aadhaar-back") : null,
                            aadhaarBackMimeType: input.aadhaarBackFile ? (input.aadhaarBackFile.mimetype ?? "application/octet-stream") : null,
                            aadhaarBackSize: input.aadhaarBackFile ? input.aadhaarBackFile.buffer.length : null,
                            aadhaarBackData: input.aadhaarBackFile ? (input.aadhaarBackFile.buffer as unknown as PartyBytes) : null,
                            panNumber: pan || null,
                            panFileName: input.panFile ? (input.panFile.originalname ?? "pan") : null,
                            panMimeType: input.panFile ? (input.panFile.mimetype ?? "application/octet-stream") : null,
                            panSize: input.panFile ? input.panFile.buffer.length : null,
                            panData: input.panFile ? (input.panFile.buffer as unknown as PartyBytes) : null,
                  },
                  select: { id: true },
          });
          resolvedPartyId = created.id;
    }
    }

    // One person per deed: block the same person being added twice (even as the other role).
    const already = await this.prisma.deedParty.findFirst({
          where: { deedId: input.deedId, partyId: resolvedPartyId },
          select: { role: true },
    });
    if (already) {
          const asRole = already.role === "buyer" ? "buyer (खरीददार)" : "seller (विक्रेता)";
          throw new BadRequestException(
                  already.role === input.role
                  ? "This person is already added to this deed."
                  : "This person is already on this deed as " + asRole + ". The same person can't be both buyer and seller.",
                  );
    }

    const link = await this.prisma.deedParty.create({
          data: { deedId: input.deedId, partyId: resolvedPartyId, role: input.role },
          select: { id: true, role: true, party: { select: PARTY_META } },
    });
    return { linkId: link.id, role: link.role as PartyRole, party: toPartyMeta(link.party) };
}

/** Remove a person from a deed (keeps them on file for other deeds). */
async removeDeedParty(deedId: string, linkId: string): Promise<void> {
    const link = await this.prisma.deedParty.findUnique({
          where: { id: linkId },
          select: { deedId: true },
    });
    if (!link || link.deedId !== deedId) throw new NotFoundException("Link not found.");
    await this.prisma.deedParty.delete({ where: { id: linkId } });
}

// ---- Naxa (per-deed property map) ----

async listNaxa(deedId: string): Promise<NaxaMeta[]> {
    const rows = await this.prisma.deedNaxa.findMany({
          where: { deedId },
          orderBy: { createdAt: "asc" },
          select: { id: true, deedId: true, fileName: true, mimeType: true, size: true, createdAt: true },
    });
    return rows.map((r) => ({
          id: r.id,
          deedId: r.deedId,
          fileName: r.fileName,
          mimeType: r.mimeType,
          size: r.size,
          createdAt: r.createdAt.toISOString(),
    }));
}

async addNaxa(input: { deedId: string; file: UploadedDoc }): Promise<NaxaMeta> {
    const row = await this.prisma.deedNaxa.create({
          data: {
                  deedId: input.deedId,
                  fileName: input.file.originalname ?? "naxa",
                  mimeType: input.file.mimetype ?? "application/octet-stream",
                  size: input.file.buffer.length,
                  data: input.file.buffer as unknown as NaxaBytes,
          },
          select: { id: true, deedId: true, fileName: true, mimeType: true, size: true, createdAt: true },
    });
    return {
          id: row.id,
          deedId: row.deedId,
          fileName: row.fileName,
          mimeType: row.mimeType,
          size: row.size,
          createdAt: row.createdAt.toISOString(),
    };
}

async naxaFile(id: string): Promise<{ fileName: string; mimeType: string; data: Buffer }> {
    const row = await this.prisma.deedNaxa.findUnique({
          where: { id },
          select: { fileName: true, mimeType: true, data: true },
    });
    if (!row) throw new NotFoundException("Naxa not found.");
    return { fileName: row.fileName, mimeType: row.mimeType, data: Buffer.from(row.data) };
}

async removeNaxa(deedId: string, id: string): Promise<void> {
    const row = await this.prisma.deedNaxa.findUnique({
          where: { id },
          select: { deedId: true },
    });
    if (!row || row.deedId !== deedId) throw new NotFoundException("Naxa not found.");
    await this.prisma.deedNaxa.delete({ where: { id } });
}
}
