import { BadRequestException, Injectable, NotFoundException } from "@nestjs/common";
import type { Prisma } from "@prisma/client";
import { PrismaService } from "../prisma/prisma.service.js";
import { tenantCreateData } from "../prisma/tenant-scope.extension.js";

export type PartyRole = "buyer" | "seller";
export type PartyType = "individual" | "company";

export interface PartyMeta {
  id: string;
  name: string;
  partyType: string;
  dob: string | null;
  address: string | null;
  aadhaarNumber: string | null;
  fileName: string | null;
  mimeType: string | null;
  size: number | null;
  aadhaarBackFileName: string | null;
  aadhaarBackMimeType: string | null;
  aadhaarBackSize: number | null;
  panNumber: string | null;
  panFileName: string | null;
  panMimeType: string | null;
  panSize: number | null;
  createdAt: string;
}

export interface DeedPartyItem {
  linkId: string;
  role: PartyRole;
  party: PartyMeta;
}

export interface NaxaMeta {
  id: string;
  deedId: string;
  fileName: string;
  mimeType: string;
  size: number;
  createdAt: string;
}

interface UploadedDoc {
  buffer: Buffer;
  originalname?: string;
  mimetype?: string;
}

const PARTY_META = {
  id: true,
  name: true,
  partyType: true,
  dob: true,
  address: true,
  aadhaarNumber: true,
  fileName: true,
  mimeType: true,
  size: true,
  aadhaarBackFileName: true,
  aadhaarBackMimeType: true,
  aadhaarBackSize: true,
  panNumber: true,
  panFileName: true,
  panMimeType: true,
  panSize: true,
  createdAt: true,
} as const;

function toPartyMeta(r: {
  id: string;
  name: string;
  partyType: string;
  dob: string | null;
  address: string | null;
  aadhaarNumber: string | null;
  fileName: string | null;
  mimeType: string | null;
  size: number | null;
  aadhaarBackFileName: string | null;
  aadhaarBackMimeType: string | null;
  aadhaarBackSize: number | null;
  panNumber: string | null;
  panFileName: string | null;
  panMimeType: string | null;
  panSize: number | null;
  createdAt: Date;
}): PartyMeta {
  return {
    id: r.id,
    name: r.name,
    partyType: r.partyType,
    dob: r.dob,
    aadhaarNumber: r.aadhaarNumber,
    fileName: r.fileName,
    mimeType: r.mimeType,
    size: r.size,
    aadhaarBackFileName: r.aadhaarBackFileName,
    address: r.address,
    aadhaarBackMimeType: r.aadhaarBackMimeType,
    aadhaarBackSize: r.aadhaarBackSize,
    panNumber: r.panNumber,
    panFileName: r.panFileName,
    panMimeType: r.panMimeType,
    panSize: r.panSize,
    createdAt: r.createdAt.toISOString(),
  };
}

/** Digits-only Aadhaar (strips spaces/dashes users may type). */
function normalizeAadhaar(raw: string): string {
  return (raw ?? "").replace(/[^0-9]/g, "");
}

/** Uppercase alphanumeric PAN (strips spaces/dashes users may type). */
function normalizePan(raw: string): string {
  return (raw ?? "").replace(/[^a-zA-Z0-9]/g, "").toUpperCase();
}

/** Bytes column value. Prisma's generated Bytes type is stricter than Node's Buffer under the current @types/node, so cast through the exact create-input field type. */
type PartyBytes = Prisma.PartyCreateInput["data"];
type NaxaBytes = Prisma.DeedNaxaCreateInput["data"];

/**
 * Aadhaar/PAN cards (reusable "people" or "companies", deduped by Aadhaar or
 * PAN number) and per-deed property maps (naxa). All bytes live in Postgres
 * because the API host has no persistent disk, so filesystem uploads
 * wouldn't survive a redeploy.
 */
@Injectable()
export class DeedDocumentsService {
  constructor(private readonly prisma: PrismaService) {}

  // ---- Parties (reusable people/companies, deduped by Aadhaar or PAN) ----

  /** Search existing people/companies by name, Aadhaar number, or PAN number, for the reuse picker. */
  async searchParties(query: string): Promise<PartyMeta[]> {
    const q = (query ?? "").trim();
    const digits = normalizeAadhaar(q);
    const pan = normalizePan(q);
    const rows = await this.prisma.party.findMany({
      where: q
        ? {
            OR: [
              { name: { contains: q, mode: "insensitive" } },
              ...(digits ? [{ aadhaarNumber: { contains: digits } }] : []),
              ...(pan ? [{ panNumber: { contains: pan } }] : []),
            ],
          }
        : {},
      orderBy: { name: "asc" },
      take: 20,
      select: PARTY_META,
    });
    return rows.map(toPartyMeta);
  }

  /** Aadhaar card (front) bytes for one person. */
  async partyFile(id: string): Promise<{ fileName: string; mimeType: string; data: Buffer }> {
    const row = await this.prisma.party.findUnique({
      where: { id },
      select: { fileName: true, mimeType: true, data: true },
    });
    if (!row) throw new NotFoundException("Person not found.");
    if (!row.data) throw new NotFoundException("No Aadhaar card on file for this person.");
    return {
      fileName: row.fileName ?? "aadhaar",
      mimeType: row.mimeType ?? "application/octet-stream",
      data: Buffer.from(row.data),
    };
  }

  /** Aadhaar card (back) bytes for one person. */
  async aadhaarBackFile(id: string): Promise<{ fileName: string; mimeType: string; data: Buffer }> {
    const row = await this.prisma.party.findUnique({
      where: { id },
      select: { aadhaarBackFileName: true, aadhaarBackMimeType: true, aadhaarBackData: true },
    });
    if (!row) throw new NotFoundException("Person not found.");
    if (!row.aadhaarBackData) throw new NotFoundException("No Aadhaar card (back) on file for this person.");
    return {
      fileName: row.aadhaarBackFileName ?? "aadhaar-back",
      mimeType: row.aadhaarBackMimeType ?? "application/octet-stream",
      data: Buffer.from(row.aadhaarBackData),
    };
  }

  /** PAN card bytes for one person/company. */
  async panFile(id: string): Promise<{ fileName: string; mimeType: string; data: Buffer }> {
    const row = await this.prisma.party.findUnique({
      where: { id },
      select: { panFileName: true, panMimeType: true, panData: true },
    });
    if (!row) throw new NotFoundException("Person not found.");
    if (!row.panData) throw new NotFoundException("No PAN card on file for this person.");
    return {
      fileName: row.panFileName ?? "pan",
      mimeType: row.panMimeType ?? "application/octet-stream",
      data: Buffer.from(row.panData),
    };
  }

  /**
   * Server-side OCR for an Aadhaar/PAN card image via Google Cloud Vision.
   * Returns the detected plain text, which the web app then parses for the
   * name / DOB / Aadhaar / PAN. This is far more accurate on real phone photos
   * than the in-browser fallback. Requires the GOOGLE_VISION_API_KEY env var;
   * if it's unset or Vision errors, we return empty text so the client quietly
   * falls back to its own OCR — nothing breaks either way.
   */
  async ocrImage(buffer: Buffer): Promise<{ text: string; debug?: string }> {
    const key = process.env.GOOGLE_VISION_API_KEY;
    if (!key) return { text: "", debug: "no-key" };
    try {
      const res = await fetch("https://vision.googleapis.com/v1/images:annotate?key=" + key, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          requests: [
            {
              image: { content: buffer.toString("base64") },
              features: [{ type: "TEXT_DETECTION" }],
            },
          ],
        }),
      });
      const raw = await res.text();
      if (!res.ok) return { text: "", debug: "HTTP " + res.status + ": " + raw.slice(0, 300) };
      const data = JSON.parse(raw) as {
        responses?: Array<{ fullTextAnnotation?: { text?: string }; error?: { message?: string } }>;
      };
      const first = data.responses?.[0];
      const respErr = first?.error?.message;
      return {
        text: first?.fullTextAnnotation?.text ?? "",
        debug: respErr ? "resp-error: " + respErr : "ok",
      };
    } catch (e) {
      return { text: "", debug: "EXC " + ((e as Error).message || String(e)) };
    }
  }

  /**
   * Structured field extraction from a photographed Aadhaar/PAN card via
   * Claude's vision (same raw-HTTP pattern as SampleDeedsService.draftWithClaude
   * -- no SDK dependency). The caller (the party-facing legacy paper-form page)
   * supplies its own prompt describing exactly which fields to read and what
   * JSON shape to reply with; this method is a thin, generic passthrough that
   * just calls Claude and parses whatever JSON text it returns, so it works
   * for the Aadhaar-front, Aadhaar-back, and PAN prompts alike without needing
   * to know their field names. Returns { error: "..." } on any failure so the
   * frontend can show it instead of leaving fields silently blank.
   */
  async extractDocumentFields(imageBase64: string, mediaType: string, prompt: string): Promise<Record<string, unknown>> {
    const key = process.env.ANTHROPIC_API_KEY;
    if (!key) return { error: "Document reading is not set up on the server yet." };
    if (!imageBase64) return { error: "An image is required." };
    if (!prompt) return { error: "A prompt is required." };
    try {
      const res = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers: {
          "content-type": "application/json",
          "x-api-key": key,
          "anthropic-version": "2023-06-01",
        },
        body: JSON.stringify({
          model: "claude-sonnet-5",
          max_tokens: 1024,
          messages: [
            {
              role: "user",
              content: [
                { type: "image", source: { type: "base64", media_type: mediaType, data: imageBase64 } },
                { type: "text", text: prompt },
              ],
            },
          ],
        }),
      });
      const raw = await res.text();
      if (!res.ok) return { error: "HTTP " + res.status + ": " + raw.slice(0, 300) };
      const data = JSON.parse(raw) as { content?: Array<{ type?: string; text?: string }> };
      const text = data.content?.find((b) => b.type === "text")?.text?.trim() ?? "";
      const cleaned = text
        .replace(/^```json\s*/i, "")
        .replace(/^```\s*/i, "")
        .replace(/```\s*$/, "")
        .trim();
      try {
        return JSON.parse(cleaned) as Record<string, unknown>;
      } catch {
        return { error: "Could not parse the extracted fields." };
      }
    } catch (e) {
      return { error: (e as Error).message || "Document reading request failed." };
    }
  }

  // ---- Deed <-> Party links ----

  async listDeedParties(deedId: string): Promise<DeedPartyItem[]> {
    const rows = await this.prisma.deedParty.findMany({
      where: { deedId },
      orderBy: { createdAt: "asc" },
      select: { id: true, role: true, party: { select: PARTY_META } },
    });
    return rows.map((r) => ({
      linkId: r.id,
      role: r.role as PartyRole,
      party: toPartyMeta(r.party),
    }));
  }

  /**
   * Attach a buyer/seller to a deed. Either reuse an existing person/company (by
   * partyId, or by an Aadhaar/PAN number that already exists) or create a new
   * one from just a name — the Aadhaar/PAN number and the card image(s) are all
   * optional at this point. This lets a name (and number, if the deed's text
   * gave one) get saved immediately; the physical card scan can be attached
   * later, person by person, via updatePartyFiles.
   * A person can appear on a deed only once — not as both buyer and seller.
   */
  async addDeedParty(input: {
    deedId: string;
    role: PartyRole;
    partyId?: string;
    name?: string;
    partyType?: PartyType;
    dob?: string;
    address?: string;
    aadhaarNumber?: string;
    panNumber?: string;
    file?: UploadedDoc;
    aadhaarBackFile?: UploadedDoc;
    panFile?: UploadedDoc;
  }): Promise<DeedPartyItem> {
    let resolvedPartyId: string;

    if (input.partyId) {
      const found = await this.prisma.party.findUnique({
        where: { id: input.partyId },
        select: { id: true },
      });
      if (!found) throw new NotFoundException("Selected person not found.");
      resolvedPartyId = found.id;
    } else {
      const partyType: PartyType = input.partyType === "company" ? "company" : "individual";
      const aadhaar = input.aadhaarNumber ? normalizeAadhaar(input.aadhaarNumber) : "";
      const pan = input.panNumber ? normalizePan(input.panNumber) : "";

      if (aadhaar && aadhaar.length !== 12) {
        throw new BadRequestException("A valid 12-digit Aadhaar number is required.");
      }
      if (pan && !/^[A-Z]{5}[0-9]{4}[A-Z]$/.test(pan)) {
        throw new BadRequestException("A valid 10-character PAN number is required.");
      }

      const existing = await this.prisma.party.findFirst({
        where: {
          OR: [
            ...(aadhaar ? [{ aadhaarNumber: aadhaar }] : []),
            ...(pan ? [{ panNumber: pan }] : []),
          ],
        },
        select: { id: true },
      });

      if (existing) {
        resolvedPartyId = existing.id;
      } else {
        const name = (input.name ?? "").trim();
        if (!name) throw new BadRequestException("Name is required for a new person.");
        const created = await this.prisma.party.create({
          data: tenantCreateData<Prisma.PartyUncheckedCreateInput>({
            name,
            partyType,
            dob: input.dob?.trim() || null,
            address: input.address?.trim() || null,
            aadhaarNumber: aadhaar || null,
            fileName: input.file ? (input.file.originalname ?? "aadhaar") : null,
            mimeType: input.file ? (input.file.mimetype ?? "application/octet-stream") : null,
            size: input.file ? input.file.buffer.length : null,
            data: input.file ? (input.file.buffer as unknown as PartyBytes) : null,
            aadhaarBackFileName: input.aadhaarBackFile ? (input.aadhaarBackFile.originalname ?? "aadhaar-back") : null,
            aadhaarBackMimeType: input.aadhaarBackFile ? (input.aadhaarBackFile.mimetype ?? "application/octet-stream") : null,
            aadhaarBackSize: input.aadhaarBackFile ? input.aadhaarBackFile.buffer.length : null,
            aadhaarBackData: input.aadhaarBackFile ? (input.aadhaarBackFile.buffer as unknown as PartyBytes) : null,
            panNumber: pan || null,
            panFileName: input.panFile ? (input.panFile.originalname ?? "pan") : null,
            panMimeType: input.panFile ? (input.panFile.mimetype ?? "application/octet-stream") : null,
            panSize: input.panFile ? input.panFile.buffer.length : null,
            panData: input.panFile ? (input.panFile.buffer as unknown as PartyBytes) : null,
          }),
          select: { id: true },
        });
        resolvedPartyId = created.id;
      }
    }

    // One person per deed: block the same person being added twice (even as the other role).
    const already = await this.prisma.deedParty.findFirst({
      where: { deedId: input.deedId, partyId: resolvedPartyId },
      select: { role: true },
    });
    if (already) {
      const asRole = already.role === "buyer" ? "buyer (खरीददार)" : "seller (विक्रेता)";
      throw new BadRequestException(
        already.role === input.role
          ? "This person is already added to this deed."
          : "This person is already on this deed as " + asRole + ". The same person can't be both buyer and seller.",
      );
    }

    const link = await this.prisma.deedParty.create({
      data: tenantCreateData<Prisma.DeedPartyUncheckedCreateInput>({
        deedId: input.deedId,
        partyId: resolvedPartyId,
        role: input.role,
      }),
      select: { id: true, role: true, party: { select: PARTY_META } },
    });
    return { linkId: link.id, role: link.role as PartyRole, party: toPartyMeta(link.party) };
  }

  /**
   * Attach/replace the Aadhaar (front/back) and/or PAN card image(s) for an
   * already-saved person/company. Used when a party was saved from just the
   * deed's name/number (see addDeedParty) and staff scans the physical card
   * in afterwards. Only the fields for which a new file is given are
   * touched — anything already on file for the other fields is left as is.
   */
  async updatePartyFiles(id: string, input: {
    file?: UploadedDoc;
    aadhaarBackFile?: UploadedDoc;
    panFile?: UploadedDoc;
  }): Promise<PartyMeta> {
    const found = await this.prisma.party.findUnique({ where: { id }, select: { id: true } });
    if (!found) throw new NotFoundException("Person not found.");
    if (!input.file && !input.aadhaarBackFile && !input.panFile) {
      throw new BadRequestException("At least one file is required.");
    }
    const updated = await this.prisma.party.update({
      where: { id },
      data: {
        fileName: input.file ? (input.file.originalname ?? "aadhaar") : undefined,
        mimeType: input.file ? (input.file.mimetype ?? "application/octet-stream") : undefined,
        size: input.file ? input.file.buffer.length : undefined,
        data: input.file ? (input.file.buffer as unknown as PartyBytes) : undefined,
        aadhaarBackFileName: input.aadhaarBackFile ? (input.aadhaarBackFile.originalname ?? "aadhaar-back") : undefined,
        aadhaarBackMimeType: input.aadhaarBackFile ? (input.aadhaarBackFile.mimetype ?? "application/octet-stream") : undefined,
        aadhaarBackSize: input.aadhaarBackFile ? input.aadhaarBackFile.buffer.length : undefined,
        aadhaarBackData: input.aadhaarBackFile ? (input.aadhaarBackFile.buffer as unknown as PartyBytes) : undefined,
        panFileName: input.panFile ? (input.panFile.originalname ?? "pan") : undefined,
        panMimeType: input.panFile ? (input.panFile.mimetype ?? "application/octet-stream") : undefined,
        panSize: input.panFile ? input.panFile.buffer.length : undefined,
        panData: input.panFile ? (input.panFile.buffer as unknown as PartyBytes) : undefined,
      },
      select: PARTY_META,
    });
    return toPartyMeta(updated);
  }

    /**
       * Update the text fields (name, DOB, Aadhaar/PAN number) of an
          * already-saved person/company. Until this existed, edits made to a
             * party's fields after the first save (see addDeedParty) were silently
                * dropped -- the party form's auto-save only ever re-sent changed card
                   * images via updatePartyFiles, never text fields. Only fields actually
                      * provided are touched; omit a field to leave it as-is.
                         */
    async updatePartyFields(id: string, input: {
          name?: string;
          dob?: string;
      address?: string;
          aadhaarNumber?: string;
          panNumber?: string;
    }): Promise<PartyMeta> {
          const found = await this.prisma.party.findUnique({ where: { id }, select: { id: true } });
          if (!found) throw new NotFoundException("Person not found.");
          const name = input.name?.trim();
          const dob = input.dob?.trim();
      const address = input.address?.trim();
          const aadhaar = input.aadhaarNumber ? normalizeAadhaar(input.aadhaarNumber) : undefined;
          if (aadhaar && aadhaar.length !== 12) {
                  throw new BadRequestException("A valid 12-digit Aadhaar number is required.");
          }
          const pan = input.panNumber ? normalizePan(input.panNumber) : undefined;
          if (pan && !/^[A-Z]{5}[0-9]{4}[A-Z]$/.test(pan)) {
                  throw new BadRequestException("A valid 10-character PAN number is required.");
          }
          const updated = await this.prisma.party.update({
                  where: { id },
                  data: {
                            name: name || undefined,
                            dob: dob || undefined,
                    address: address || undefined,
                            aadhaarNumber: aadhaar || undefined,
                            panNumber: pan || undefined,
                  },
                  select: PARTY_META,
          });
          return toPartyMeta(updated);
    }

  /**
   * Remove a person from a deed. If they are not linked to any other deed
   * afterwards, their Aadhaar/PAN/photo record is erased entirely; if they
   * are still linked elsewhere, that record is left on file untouched so
   * the other deed(s) are unaffected.
   */
  async removeDeedParty(deedId: string, linkId: string): Promise<void> {
    const link = await this.prisma.deedParty.findUnique({
      where: { id: linkId },
      select: { deedId: true, partyId: true },
    });
    if (!link || link.deedId !== deedId) throw new NotFoundException("Link not found.");
    await this.prisma.deedParty.delete({ where: { id: linkId } });

    const stillUsedElsewhere = await this.prisma.deedParty.findFirst({
      where: { partyId: link.partyId },
      select: { id: true },
    });
    if (!stillUsedElsewhere) {
      await this.prisma.party.delete({ where: { id: link.partyId } }).catch(() => {
        // Best-effort: ignore races (e.g. concurrently re-linked or already
        // deleted) — the deed-party link above has already been removed.
      });
    }
  }

  // ---- Naxa (per-deed property map) ----

  async listNaxa(deedId: string): Promise<NaxaMeta[]> {
    const rows = await this.prisma.deedNaxa.findMany({
      where: { deedId },
      orderBy: { createdAt: "asc" },
      select: { id: true, deedId: true, fileName: true, mimeType: true, size: true, createdAt: true },
    });
    return rows.map((r) => ({
      id: r.id,
      deedId: r.deedId,
      fileName: r.fileName,
      mimeType: r.mimeType,
      size: r.size,
      createdAt: r.createdAt.toISOString(),
    }));
  }

  async addNaxa(input: { deedId: string; file: UploadedDoc }): Promise<NaxaMeta> {
    const row = await this.prisma.deedNaxa.create({
      data: tenantCreateData<Prisma.DeedNaxaUncheckedCreateInput>({
        deedId: input.deedId,
        fileName: input.file.originalname ?? "naxa",
        mimeType: input.file.mimetype ?? "application/octet-stream",
        size: input.file.buffer.length,
        data: input.file.buffer as unknown as NaxaBytes,
      }),
      select: { id: true, deedId: true, fileName: true, mimeType: true, size: true, createdAt: true },
    });
    return {
      id: row.id,
      deedId: row.deedId,
      fileName: row.fileName,
      mimeType: row.mimeType,
      size: row.size,
      createdAt: row.createdAt.toISOString(),
    };
  }

  async naxaFile(id: string): Promise<{ fileName: string; mimeType: string; data: Buffer }> {
    const row = await this.prisma.deedNaxa.findUnique({
      where: { id },
      select: { fileName: true, mimeType: true, data: true },
    });
    if (!row) throw new NotFoundException("Naxa not found.");
    return { fileName: row.fileName, mimeType: row.mimeType, data: Buffer.from(row.data) };
  }

  async removeNaxa(deedId: string, id: string): Promise<void> {
    const row = await this.prisma.deedNaxa.findUnique({
      where: { id },
      select: { deedId: true },
    });
    if (!row || row.deedId !== deedId) throw new NotFoundException("Naxa not found.");
    await this.prisma.deedNaxa.delete({ where: { id } });
  }
}
